#!/bin/bash
source base_config.rc
cat > /etc/network/interfaces <<EOF
auto lo
iface lo inet loopback
auto eth0
iface eth0 inet dhcp
auto eth1
iface eth1 inet manual
auto eth2
iface eth2 inet static
address $ip_eth2
netmask $mask_eth2
EOF
