#!/bin/bash
source base_config.rc
cat >> /etc/network/interfaces <<EOF
auto admin_bridge
iface admin_bridge inet static
address $ip_eth1
netmask $mask_eth1
gateway $dg_eth1
bridge_ports eth1
bridge_stp off
bridge_fd 2
bridge_maxwait 20
EOF
