#!/bin/bash
source base_config.rc
unset LANG
unset LANGUAGE
LC_ALL=C
export LC_ALL
#install mariadb with password
# source http://dba.stackexchange.com/questions/35866/install-mariadb-without-password-prompt-in-ubuntu
#       http://stackoverflow.com/questions/4937792/using-variables-inside-a-bash-heredoc
export DEBIAN_FRONTEND=noninteractive
debconf-set-selections -v <<EOF
mariadb-server-5.5 mysql-server/root_password password $master_pass
EOF
debconf-set-selections -v <<EOF
mariadb-server-5.5 mysql-server/root_password_again password $master_pass
EOF
apt-get install mariadb-server python-mysqldb -y
# modify the configuration files for  maria db
sed -i s/127.0.0.1/$ip_eth0/g /etc/mysql/my.cnf
sed -i '/\[mysqld\]/a character-set-server = utf8' /etc/mysql/my.cnf
sed -i "/\[mysqld\]/a init-connect = 'SET NAMES utf8'" /etc/mysql/my.cnf
sed -i '/\[mysqld\]/a collation-server = utf8_general_ci' /etc/mysql/my.cnf
sed -i '/\[mysqld\]/a default-storage-engine = innodb' /etc/mysql/my.cnf
sed -i '/\[mysqld\]/a innodb_file_per_table' /etc/mysql/my.cnf
service mysql restart
# create  loop to configure all datatbases
# source http://www.tldp.org/LDP/abs/html/loops1.html
#       http://www.bluepiccadilly.com/2011/12/creating-mysql-database-and-user-command-line-and-bash-script-automate-process
for db_and_user_name in "keystone" "glance" "nova" "neutron"
do
mysql -uroot -p$master_pass -e "create database if not exists $db_and_user_name;"
mysql -uroot -p$master_pass -e "GRANT ALL PRIVILEGES ON $db_and_user_name.* TO $db_and_user_name@'%' IDENTIFIED BY '$master_pass'"
mysql -uroot -p$master_pass -e "FLUSH PRIVILEGES;"
done
service mysql restart

