#!/bin/bash
# short intro
# source http://www.cyberciti.biz/tips/linux-unix-pause-command.html
read -p "This script will install openstack basic components (keystone,nova,neutron,glance) on a single host. Juno, ubuntu trusty, etc To be completed.U need to run it as root/sudo Press enter to continue"
## good idea stolen from devstack as I get a lot of errors on locale from lxc containers
unset LANG
unset LANGUAGE
LC_ALL=C
export LC_ALL
# source the variables
source base_config.rc
# set the network file
echo "updating the system"
apt-get update && apt-get upgrade -y
echo "installing lxc and creating the first ubuntu trusty container"
apt-get install lxc lxcctl -y
lxc-create --name base_box -t ubuntu
lxc-clone base_box database
echo "00"
./00network_config
# set the eth2 separately so that the variable would not be substituted
echo "01"
./01eth2_config
# restart networking
echo "02"
./02restart_network_config
ifconfig eth0 | awk '/inet addr:/ {print$2}' | sed 's/addr://'
ifconfig eth1 | awk '/inet addr:/ {print$2}' | sed 's/addr://'
# overwrite /etc/hosts with the new value for our hostname and  fixed ip - not pointing to 127.0.0.1
echo "03"
./03hosts_file_config
# overite the /etc/hostname with the new value
hostname $host_name
echo "04"
./04hostname_config
awk '//{print $1}' /etc/hostname
echo $HOSTNAME
# create the dns servers of google
echo "05"
./05resolvconf_config
#let's update the system
echo "06"
./06apt_config
#install maria db with root password
echo "07"
./07mariadb_config
echo "08"
./08rabbitmq_config
#####keystone#####
##################
echo "09"
./09keystone_config
echo "10"
./10glance_config
echo "11"
./11nova_config
echo "12"
./12neutron_config
