#!/bin/bash
read -p "This script will install the openstack nova compute on a single host. Press enter to continue"
source base_config.rc
source admin-openrc.sh
echo "20"
./20nova_compute_config
lxc-attach -n nova -- nova service-list > nova-test
