#!/bin/bash
# short intro
# source http://www.cyberciti.biz/tips/linux-unix-pause-command.html
read -p "This script will install the openstack nova compute on a single host. Press enter to continue"
## good idea stolen from devstack as I get a lot of errors on locale from lxc containers
#unset LANG
#unset LANGUAGE
#LC_ALL=C
#export LC_ALL
# source the variables
source base_config.rc
echo "updating the system"
# add the ubuntu cloud ring support for juno
echo "deb http://ubuntu-cloud.archive.canonical.com/ubuntu" \
  "trusty-updates/juno main" > /etc/apt/sources.list.d/cloudarchive-juno.list
# add the key 
#https://github.com/dguitarbite/OpenStack-Folsom-VM-SandBox-Guide/issues/5
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5EDB1B62EC4926EA
apt-get update && apt-get install ubuntu-cloud-keyring -y 
echo "00"
./00network_config
# set the eth2 separately so that the variable would not be substituted
echo "01"
./01eth2_config
echo "011"
./011eth3_bridge_config
# restart networking
echo "02"
./02restart_network_config
ifconfig eth0 | awk '/inet addr:/ {print$2}' | sed 's/addr://'
ifconfig eth1 | awk '/inet addr:/ {print$2}' | sed 's/addr://'
# overwrite /etc/hosts with the new value for our hostname and  fixed ip - not pointing to 127.0.0.1
echo "03"
#./03hosts_file_config
# overite the /etc/hostname with the new value
#hostname $host_name
#echo "04"
#./04hostname_config
awk '//{print $1}' /etc/hostname
echo $HOSTNAME
# create the dns servers of google
echo "05"
./05resolvconf_config
echo "creating the admin credentials"
cat > admin-openrc.sh <<EOF
export OS_TENANT_NAME=admin
export OS_USERNAME=admin
export OS_PASSWORD=$master_pass
export OS_AUTH_URL=http://$keystone_ip:35357/v2.0
EOF
echo "20"
./20nova_compute_config
